import cv2
import numpy as np
import mediapipe as mp
import os

# --- Configuration for 19 Joints based on the 25-point model ---
# Each tuple is: (joint_name, point1_idx, point2_idx, point3_idx)
# The indices now correspond to the 25-point model generated by our PoseExtractor.
JOINT_CONFIG_25 = [
    # LOWER BODY (8 joints)
    ('left_hip_yaw', 8, 12, 9),       # Yaw of the left hip (mid_hip, l_hip, r_hip)
    ('left_hip_pitch', 8, 12, 14),   # Pitch of the left hip (mid_hip, l_hip, l_ankle)
    ('left_knee', 12, 13, 14),       # Left knee (l_hip, l_knee, l_ankle)
    ('left_ankle', 13, 14, 19),      # Left ankle (l_knee, l_ankle, l_big_toe)
    ('right_hip_yaw', 8, 9, 12),     # Yaw of the right hip (mid_hip, r_hip, l_hip)
    ('right_hip_pitch', 8, 9, 11),   # Pitch of the right hip (mid_hip, r_hip, r_ankle)
    ('right_knee', 9, 10, 11),       # Right knee (r_hip, r_knee, r_ankle)
    ('right_ankle', 10, 11, 22),     # Right ankle (r_knee, r_ankle, r_big_toe)
    # UPPER BODY (11 joints)
    ('spine_pitch', 8, 1, 0),        # Spine pitch (mid_hip, neck, nose)
    ('neck_pitch', 1, 0, 15),        # Neck pitch (neck, nose, r_eye)
    ('neck_yaw', 15, 0, 16),         # Neck yaw (r_eye, nose, l_eye)
    ('left_shoulder_pitch', 1, 5, 7), # Left shoulder pitch (neck, l_shoulder, l_wrist)
    ('left_shoulder_roll', 5, 7, 6),  # Left shoulder roll (l_shoulder, l_wrist, l_elbow)
    ('left_elbow', 5, 6, 7),         # Left elbow (l_shoulder, l_elbow, l_wrist)
    ('left_wrist', 6, 7, 19),        # Left wrist (l_elbow, l_wrist, l_big_toe - as a reference point)
    ('right_shoulder_pitch', 1, 2, 4),# Right shoulder pitch (neck, r_shoulder, r_wrist)
    ('right_shoulder_roll', 2, 4, 3), # Right shoulder roll (r_shoulder, r_wrist, r_elbow)
    ('right_elbow', 2, 3, 4),        # Right elbow (r_shoulder, r_elbow, r_wrist)
    ('right_wrist', 3, 4, 22),       # Right wrist (r_elbow, r_wrist, r_big_toe - as a reference point)
]

def load_image(file_path: str) -> np.ndarray:
    """Loads an image from a file path and converts it to RGB float32 format."""
    image_bgr = cv2.imread(file_path)
    if image_bgr is None:
        raise FileNotFoundError(f"Image not found at {file_path}")
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    return image_rgb.astype(np.float32) / 255.0

def preprocess_image(image: np.ndarray, target_size=(256, 256)) -> np.ndarray:
    """Resizes the image for pose estimation."""
    return cv2.resize(image, target_size)

class PoseExtractor:
    """Extracts 33 keypoints from an image using MediaPipe."""
    def __init__(self):
        self.pose = mp.solutions.pose
        self.detector = self.pose.Pose(static_image_mode=True, model_complexity=2, min_detection_confidence=0.5)

    def extract_keypoints(self, image: np.ndarray) -> np.ndarray:
        """Processes an image and returns Body25-like keypoints."""
        results = self.detector.process((image * 255).astype(np.uint8))
        if not results.pose_landmarks:
            return []
        
        landmarks = results.pose_landmarks.landmark
        keypoints_33 = np.array([[lm.x, lm.y, lm.z, lm.visibility] for lm in landmarks])

        # Map MediaPipe's 33 points to a Body25-like format
        def avg(i, j): return (keypoints_33[i] + keypoints_33[j]) / 2.0
        
        body25 = [
            keypoints_33[0],            # 0 Nose
            avg(11, 12),                # 1 Neck
            keypoints_33[12],           # 2 RShoulder
            keypoints_33[14],           # 3 RElbow
            keypoints_33[16],           # 4 RWrist
            keypoints_33[11],           # 5 LShoulder
            keypoints_33[13],           # 6 LElbow
            keypoints_33[15],           # 7 LWrist
            avg(23, 24),                # 8 MidHip
            keypoints_33[24],           # 9 RHip
            keypoints_33[26],           # 10 RKnee
            keypoints_33[28],           # 11 RAnkle
            keypoints_33[23],           # 12 LHip
            keypoints_33[25],           # 13 LKnee
            keypoints_33[27],           # 14 LAnkle
            keypoints_33[2],            # 15 REye
            keypoints_33[5],            # 16 LEye
            keypoints_33[8],            # 17 REar
            keypoints_33[7],            # 18 LEar
            keypoints_33[32],           # 19 LBigToe
            keypoints_33[31],           # 20 LSmallToe
            keypoints_33[29],           # 21 LHeel
            keypoints_33[28],           # 22 RBigToe
            keypoints_33[27],           # 23 RSmallToe
            keypoints_33[30]            # 24 RHeel
        ]
        return np.array(body25)

def _unit(v): return v / (np.linalg.norm(v) + 1e-6)
def _angle_between(v1, v2): return np.arccos(np.clip(np.dot(_unit(v1), _unit(v2)), -1.0, 1.0))

def _calculate_joint_angle(joint_name, p1_idx, p2_idx, p3_idx, keypoints):
    """Calculates a specific joint angle from keypoints."""
    # Check if all required keypoints are present and visible
    if any(keypoints[i][3] < 0.5 for i in {p1_idx, p2_idx, p3_idx}):
        return 0.0 # Return a neutral angle if keypoints are not visible

    p1, p2, p3 = keypoints[p1_idx][:3], keypoints[p2_idx][:3], keypoints[p3_idx][:3]
    
    if 'hip_yaw' in joint_name or 'neck_yaw' in joint_name:
        v = _unit(p2 - p1)
        return np.arctan2(v[0], v[2])
    elif 'hip_pitch' in joint_name or 'spine_pitch' in joint_name or 'neck_pitch' in joint_name or 'shoulder_pitch' in joint_name:
        v = _unit(p2 - p1)
        return np.arctan2(-v[1], v[2])
    elif 'shoulder_roll' in joint_name:
        v1 = _unit(p1 - p2) # Vector from shoulder to elbow/wrist
        v2 = np.array([0, 0, 1]) # Forward vector
        return np.arctan2(v1[0], v1[1])
    elif 'knee' in joint_name or 'elbow' in joint_name or 'ankle' in joint_name or 'wrist' in joint_name:
        v1, v2 = _unit(p2 - p1), _unit(p3 - p2)
        return _angle_between(v1, v2)
    return 0.0

def body25_to_pose19(body25_keypoints):
    """Converts Body25 keypoints to a 19-joint angle vector."""
    if len(body25_keypoints) == 0:
        return np.zeros(19, dtype=np.float32)
        
    pose_19 = np.zeros(19, dtype=np.float32)
    for i, (joint_name, p1, p2, p3) in enumerate(JOINT_CONFIG_25):
        pose_19[i] = _calculate_joint_angle(joint_name, p1, p2, p3, body25_keypoints)
    return pose_19

def get_initial_pose_from_image(image_path: str) -> np.ndarray:
    """
    High-level function to get a 19-joint pose from an image file.
    Returns a zero vector if no pose is detected.
    """
    try:
        image = load_image(image_path)
        preprocessed = preprocess_image(image)
        extractor = PoseExtractor()
        body25_kp = extractor.extract_keypoints(preprocessed)
        if len(body25_kp) > 0:
            return body25_to_pose19(body25_kp)
        else:
            print(f"Warning: No pose detected in {image_path}.")
            return np.zeros(19, dtype=np.float32)
    except Exception as e:
        print(f"Error processing image {image_path}: {e}")
        return np.zeros(19, dtype=np.float32)
